export var Globals = {
  inicioSesion: false,
  usuario: '',
  rolUser: '',
  imagen: '',
  imagenVista: '',
  ventana: 0,
  pagina: 0,
  movil: false,
  mostrarRouterOutlet: true,
  filtroActivo: false,
  filtroUN: false,
  filtroEstatusUN: false,
  filtroAreasUN: false,
  datosFiltrados: 0,
  registrosBitacora: [],
  editar: false,
  numRegBitacora: 0,
  filtroBitacora: 0,
  usuarioEdicion: {},
  editarUsuario: false,
  editarRoles: false,
  permisos: [] as any[],
  url: '',
  pantallasSeleccionadas: [] as any[],
  cerrarSesion: false,
  cambioEstatus: false,
  reestableceContrasenia: false,
  eliminarRol: false
};
